require("knothc.set")
require("knothc.remap")
require("knothc.tokyonight")
require("knothc.lualine")
require("knothc.nvim-tree")
require("knothc.toggleterm")
require("knothc.treesitter")
require("knothc.cmp")
require("knothc.telescope")

print("lua/knothc/init loaded...")
