# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# [character]
# success_symbol = "[➜](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"

[directory]
truncation_symbol = ".../"
read_only = " "

[aws]
format = '[\[$symbol($profile)(\($region\))(\[$duration\])\]](bright-black)'
symbol = "  "

[bun]
format = '[\[$symbol($version)\]](bright-black)'

[c]
format = '[\[$symbol($version(-$name))\]](bright-black)'
symbol = " "

[cmake]
format = '[\[$symbol($version)\]](bright-black)'

[cmd_duration]
format = '[\[祥$duration\]](bright-black)'

[cobol]
format = '[\[$symbol($version)\]](bright-black)'

[conda]
format = '[\[$symbol$environment\]](bright-black)'
symbol = " "

[crystal]
format = '[\[$symbol($version)\]](bright-black)'

[daml]
format = '[\[$symbol($version)\]](bright-black)'

[dart]
format = '[\[$symbol($version)\]](bright-black)'
symbol = " "

[deno]
format = '[\[$symbol($version)\]](bright-black)'

[docker_context]
format = '[\[$symbol$context\]](bright-black)'
symbol = " "

[dotnet]
format = '[\[$symbol($version)(🎯 $tfm)\]](bright-black)'

[elixir]
format = '[\[$symbol($version \(OTP $otp_version\))\]](bright-black)'
symbol = " "

[elm]
format = '[\[$symbol($version)\]](bright-black)'
symbol = " "

[erlang]
format = '[\[$symbol($version)\]](bright-black)'

[gcloud]
format = '[\[$symbol$account(@$domain)(\($region\))\]](bright-black)'

[git_branch]
# format = '[\[$symbol$branch\]](bold purple)'
symbol = " "

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'
style = "bright-black"

[golang]
format = '[\[$symbol($version)\]](bright-black)'
symbol = " "

[haskell]
format = '[\[$symbol($version)\]](bright-black)'

[helm]
format = '[\[$symbol($version)\]](bright-black)'

[hg_branch]
format = '[\[$symbol$branch\]](bright-black)'

[java]
format = '[\[$symbol($version)\]](bright-black)'

[julia]
format = '[\[$symbol($version)\]](bright-black)'

[kotlin]
format = '[\[$symbol($version)\]](bright-black)'

[kubernetes]
format = '[\[$symbol$context( \($namespace\))\]](bright-black)'

[lua]
format = '[\[$symbol($version)\]](bright-black)'
symbol = " "

[memory_usage]
format = '\[$symbol[$ram( | $swap)\]](bright-black)'

[meson]
format = '[\[$symbol$project\]](bright-black)'

[nim]
format = '[\[$symbol($version)\]](bright-black)'

[nix_shell]
format = '[\[$symbol$state( \($name\))\]](bright-black)'

[nodejs]
format = '[\[$symbol($version)\]](bright-black)'
symbol = " "

[ocaml]
format = '[\[$symbol($version)(\($switch_indicator$switch_name\))\]](bright-black)'

[openstack]
format = '[\[$symbol$cloud(\($project\))\]](bright-black)'

[package]
format = '[\[$symbol$version\]](bright-black)'

[perl]
format = '[\[$symbol($version)\]](bright-black)'

[php]
format = '[\[$symbol($version)\]](bright-black)'

[pulumi]
format = '[\[$symbol$stack\]](bright-black)'

[purescript]
format = '[\[$symbol($version)\]](bright-black)'

[python]
#format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))\]](bright-black)'
format = '[\[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))\]](bright-black)'
symbol = " "

[raku]
format = '[\[$symbol($version-$vm_version)\]](bright-black)'

[red]
format = '[\[$symbol($version)\]](bright-black)'

[ruby]
format = '[\[$symbol($version)\]](bright-black)'
symbol = " "

[rust]
format = '[\[$symbol($version)\]](bright-black)'
symbol = " "

[scala]
format = '[\[$symbol($version)\]](bright-black)'

[spack]
format = '[\[$symbol$environment\]](bright-black)'

[sudo]
format = '\[[as $symbol]\]'

[swift]
format = '[\[$symbol($version)\]](bright-black)'

[terraform]
format = '[\[$symbol$workspace\]](bright-black)'

[time]
format = '[\[$time\]](bright-black)'

[username]
format = '\[[$user\]](bright-black)'

[vagrant]
format = '[\[$symbol($version)\]](bright-black)'

[vlang]
format = '[\[$symbol($version)\]](bright-black)'

[zig]
format = '[\[$symbol($version)\]](bright-black)'
